routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false,
    'confirm' => false

]);

// level admin
Route::middleware(['auth', 'checkuser:admin'])->group(function () {
    Route::resource('user', UserController::class);
});

// level  all user
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('home');
    });

    Route::resources([
        'category' => CategoryController::class,
        'product' => ProductController::class,
        'customer' => CustomerController::class,
        'order' => OrderController::class

    ]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'level',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Fungsi untuk validasi form
     *
     * @param Request $request
     * @return void
     */
    public function validateForm($request, $id = null)
    {
        if ($request->isMethod('post')) {
            $rules = [
                'password' => 'required|max:16',
                'email' => 'required|max:65|email|unique:users, email'

            ];
        } else {
            $rules = [
                'email' => 'required|max:65|email|unique:users, email,' . $id
            ];
        }

        $this->validate($request, [
            'name' => 'required|between:5,65',
            'phone' => 'required|max:15',
        ] + $rules);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            $users = User::select('id', 'name', 'email', 'phone', 'level');

            return Datatables::of($users)
                ->addColumn('action', function ($user) {
                    return '
                        <a href="' . route('user.edit', [$user->id]) . '"
                            class="btn btn-sm btn-primary">
                            <i class="fas fa-edit"></i>
                            Edit
                        </a>

                        <a href="' . route('user.destroy', [$user->id]) . '"
                            class="btn btn-sm btn-danger"
                            data-confirm="Apakah anda yakin?">
                            <i class="fas fa-trash"></i>
                            Hapus
                        </a>
                    ';
                })
                ->addIndexColumn()
                ->toJson();
        }

        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            User::create($request->except('password') + [
                'password' => encrypt($request->input('password'))
            ]);

            $status = [
                'status' => 'success',
                'message' => 'Data berhasil disimpan'
            ];
        } catch (\Exception $e) {
            $status = [
                'status' => 'error',
                'message' => $e->getMessage()
            ];
        }

        return redirect('user')->with($status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact($user));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->validateForm($request, $user->id);

        try {
            $user->update($request->all());

            $status = [
                'status' => 'success',
                'message' => 'Data berhasil diupdate'
            ];
        } catch (\Exception $e) {
            //exception $e;
            $status = [
                'status' => 'error',
                'message' => $e->getMessage()
            ];
        }
        return redirect('category')->with($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.main')

@section('title', 'User')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item"><a href="{{ route('user.index') }}">Daftar User</a></li>
<li class="breadcrumb-item active">Tambah User</li>
@endsection

@section('content')
<div class="card">
    <div class="card-header">Tambah User</div>
    <div class="card-body">
        <div class="container">
            <form action="{{ route('user.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Nama Lengkap</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror"
                        id="name" name="name" value="{{ old('name') }}"
                        placeholder="Nama Lengkap">
                        @error('name')
                            <label for="name" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <label for="email">Alamat Email</label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror"
                        id="email" name="email" value="{{ old('email') }}"
                        placeholder="Alamat lengkap">
                        @error('email')
                            <label for="email" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <label for="phone">No. Telepon</label>
                    <input type="phone" class="form-control @error('phone') is-invalid @enderror"
                        id="phone" name="phone" value="{{ old('phone') }}"
                        placeholder="No. Telepon">
                        @error('phone')
                            <label for="phone" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <label for="level">Level</label>
                    <select name="level" id="level" class="form-control">
                        <option value="user" {{ (old('level') == 'user' ? 'selected' : '') }}>User</option>
                        <option value="admin" {{ (old('level') == 'admin' ? 'selected' : '') }}>Administrator</option>
                    </select>
                        @error('email')
                            <label for="email" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-save"></i> Submit</button>
                    <a href="{{ route('category.index') }}" class="btn btn-danger btn-sm"><i class="fas fa-redo-alt"></i> Batal</a>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

@push('script')
@endpush

resources/views/users/edit.blade.php
@extends('layouts.main')

@section('title', 'Kategori Produk')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item"><a href="{{ route('category.index') }}">Daftar Kategori</a></li>
<li class="breadcrumb-item active">Edit Kategori</li>
@endsection

@section('content')
<div class="card">
    <div class="card-header">Edit Kategori</div>
    <div class="card-body">
        <div class="container">
            <form action="{{  route('user.update', [$user->id]) }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Nama Lengkap</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror"
                        id="name" name="name" value="{{ old('name') }}"
                        value="{{ $user->name }}" placeholder="Nama Lengkap">
                        @error('name')
                            <label for="name" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <label for="email">Alamat Email</label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror"
                        id="email" name="email" value="{{ old('email') }}"
                        value="{{ $user->email }}" placeholder="Alamat lengkap">
                        @error('email')
                            <label for="email" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <label for="phone">No. Telepon</label>
                    <input type="phone" class="form-control @error('phone') is-invalid @enderror"
                        id="phone" name="phone" value="{{ old('phone') }}"
                        value="{{ $user->phone }}" placeholder="No. Telepon">
                        @error('phone')
                            <label for="phone" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <label for="level">Level</label>
                    <select name="level" id="level" class="form-control">
                        <option value="user" {{ (old('level') == 'user' ? 'selected' : '') }}>User</option>
                        <option value="admin" {{ (old('level') == 'admin' ? 'selected' : '') }}>Administrator</option>
                    </select>
                        @error('email')
                            <label for="email" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-save"></i> Submit</button>
                    <a href="{{ route('category.index') }}" class="btn btn-danger btn-sm"><i class="fas fa-redo-alt"></i> Batal</a>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

@push('script')
@endpush

resources/views/users/index.blade.php
@extends('layouts.main')

@section('title', 'User')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item active">User</li>
@endsection

@section('content')

<div class="card">
    <div class="card-header">Daftar User</div>
    <div class="card-body">
        <div class="form-group">
            <a href="{{ route('user.create') }}" class="btn btn-success btn-sm">
                <i class="fas fa-plus-circle"></i>
                Tambah</a>
        </div>

        <div class="form-group">
            <table id="table_users" class="table table-striped">
                <thead>
                    <tr>
                        <th width="10%">No.</th>
                        <th>Nama</th>
                        <th>Email</th>
                        <th>No. Telepon</th>
                        <th>level</th>
                        <th width="25%">Aksi</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
<script>
    var table = $("#table_users").DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ route('user.index') }}',
        order: [[1, 'asc']],
        columns: [
            {data: 'DT_RowIndex', searchable: 'false', orderable: 'false'},
            {data: 'name'},
            {data: 'email'},
            {data: 'phone'},
            {data: 'level'},
            {data: 'action', searchable: 'false', orderable: 'false'}
        ],
        // columnDefs: [
        //     {
        //         orderable: true,
        //         className: 'reorder',
        //         targets: 1,
        //     },
        //     {
        //         orderable: false,
        //         targets: '_all'
        //     }
        // ]
        drawCallback: function() {
            confirmDelete();
        }

    });

</script>
@endpush

resources/views/users/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form action="{{ route('login') }}" method="post">
        @csrf
        <div class="input-group mb-3">
          <input type="email" class="form-control" name="email" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" name="password" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      {{-- <div class="social-auth-links text-center mb-3">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div> --}}
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="forgot-password.html">I forgot my password</a>
      </p>
      <p class="mb-0">
        <a href="register.html" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('js/adminlte.min.js') }}"></script>

</body>
</html>