routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false,
    'confirm' => false

]);

// level admin
Route::middleware(['auth', 'checkuser:admin'])->group(function () {
    Route::resource('user', UserController::class);
});

// level  all user
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('home');
    });

    Route::resources([
        'category' => CategoryController::class,
        'product' => ProductController::class,
        'customer' => CustomerController::class,
        'order' => OrderController::class

    ]);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_name',
    ];

    /**
     * Get all of the products for the Category
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products(): HasMany
    {
        return $this->hasMany(Category::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{

    /**
     * Fungsi untuk validasi form
     *
     * @param Request $request
     * @return void
     */
    public function validateForm($request)
    {
        $this->validate($request, [
            'category_name' => 'required|max:30'
        ], [
            'category_name.required' => 'Nama kategori tidak boleh kosong',
            'category_name.max' => 'Panjang maksimum 30 karakter'
        ]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $categories = Category::select('id', 'category_name');

            return Datatables::of($categories)
                ->addColumn('action', function ($category) {
                    return '
                        <a href="' . route('category.edit', [$category->id]) . '"
                            class="btn btn-sm btn-primary">
                            <i class="fas fa-edit"></i>
                            Edit
                        </a>

                        <a href="' . route('category.destroy', [$category->id]) . '"
                            class="btn btn-sm btn-danger"
                            data-confirm="Apakah anda yakin?">
                            <i class="fas fa-trash"></i>
                            Hapus
                        </a>
                    ';
                })
                ->addIndexColumn()
                ->toJson();
        }

        return view('categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateForm($request);

        try {
            Category::create($request->all());

            $status = [
                'status' => 'success',
                'message' => 'Data berhasil disimpan'
            ];
        } catch (\Exception $e) {
            $status = [
                'status' => 'error',
                'message' => $e->getMessage()
            ];
        }

        return redirect('category')->with($status);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        dd($category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validateForm($request);
        try {
            $category->update($request->all());

            $status = [
                'status' => 'success',
                'message' => 'Data berhasil diupdate'
            ];
        } catch (\Exception $e) {
            //exception $e;
            $status = [
                'status' => 'error',
                'message' => $e->getMessage()
            ];
        }
        return redirect('category')->with($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $result = $category->delete();

        if ($result > 0) {
            $response = [
                'status' => 'success',
                'message' => 'Kategori berhasil dihapus'
            ];
        } else {
            $response = [
                'status' => 'success',
                'message' => 'Gagal menghapus kategori'
            ];
        }

        return response()->json($response);
    }
}

resources/views/categories/create.blade.php
@extends('layouts.main')

@section('title', 'Kategori Produk')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item"><a href="{{ route('category.index') }}">Daftar Kategori</a></li>
<li class="breadcrumb-item active">Tambah Kategori</li>
@endsection

@section('content')
<div class="card">
    <div class="card-header">Tambah Kategori</div>
    <div class="card-body">
        <div class="container">
            <form action="{{ route('category.store') }}" method="post">
                @csrf

                <div class="form-group">
                    <label for="category_name">Nama Kategori</label>
                    <input type="text" class="form-control @error('category_name') is-invalid @enderror"
                        id="category_name" name="category_name" value="{{ old('category_name') }}"
                        placeholder="Nama Kategori">
                        @error('category_name')
                            <label for="category_name" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    <a href="{{ route('category.index') }}" class="btn btn-danger btn-sm">Batal</a>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

@push('script')
@endpush

resources/views/categories/edit.blade.php
@extends('layouts.main')

@section('title', 'Kategori Produk')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item"><a href="{{ route('category.index') }}">Daftar Kategori</a></li>
<li class="breadcrumb-item active">Edit Kategori</li>
@endsection

@section('content')
<div class="card">
    <div class="card-header">Edit Kategori</div>
    <div class="card-body">
        <div class="container">
            <form action="{{ route('category.update', [$category->id]) }}" method="post">
                @csrf
                @method('put')

                <div class="form-group">
                    <label for="category_name">Nama Kategori</label>
                    <input type="text" class="form-control @error('category_name') is-invalid @enderror" id="category_name" name="category_name"
                        placeholder="Nama Kategori" value="{{ $category->category_name }}">
                        @error('category_name')
                            <label for="category_name" class="invalid-feedback">{{ $message }}</label>
                        @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                    <a href="{{ route('category.index') }}" class="btn btn-danger btn-sm">Batal</a>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

@push('script')
@endpush

resources/views/categories/index.blade.php
@extends('layouts.main')

@section('title', 'Kategori Produk')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Home</a></li>
<li class="breadcrumb-item active">Kategori Produk</li>
@endsection

@section('content')

{{-- @if (session('status'))
<div class="alert {{ session('status') == 'success' ? 'alert-success' : 'alert-danger' }}">
    {{ session('message') }}
</div>
@endif --}}

<div class="card">
    <div class="card-header">Daftar Kategori</div>
    <div class="card-body">
        <div class="form-group">
            <a href="{{ route('category.create') }}" class="btn btn-success btn-sm">
                <i class="fas fa-plus-circle"></i>
                Tambah</a>
        </div>

        <div class="table-responsive form-group">
            <table id="table_categories" class="table table-striped">
                <thead>
                    <tr>
                        <th width="10%">No.</th>
                        <th>Nama Kategori</th>
                        <th width="25%">Aksi</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('script')
<script>
    var table = $("#table_categories").DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ route('category.index') }}',
        order: [[1, 'asc']],
        columns: [
            {data: 'DT_RowIndex', searchable: 'false', orderable: 'false'},
            {data: 'category_name'},
            {data: 'action', searchable: 'false', orderable: 'false'}
        ],
        // columnDefs: [
        //     {
        //         orderable: true,
        //         className: 'reorder',
        //         targets: 1,
        //     },
        //     {
        //         orderable: false,
        //         targets: '_all'
        //     }
        // ]
        drawCallback: function() {
            confirmDelete();
        }

    });

</script>
@endpush